name: Build and Draft Release
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: The released version without 'v'. For example, 1.0.0.
permissions:
  contents: write
env:
  VERSION: ${{ github.event.inputs.version }}
jobs:
  draft_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.x"
      - name: Set up Git name and email
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
      - name: Build assets and draft release
        run: bash ./scripts/draftrelease.bash
        env:
          GH_TOKEN:  ${{ secrets.GITHUB_TOKEN }}
          WEBHOOK_URL: ${{ secrets.SLACK_RELEASE_NOTIFICATION_WEBHOOK }}
          RELEASE_MINISIGN_PRIVATE_KEY: ${{secrets.RELEASE_MINISIGN_PRIVATE_KEY}}
          RELEASE_MINISIGN_PRIVATE_KEY_PASSWORD: ${{secrets.RELEASE_MINISIGN_PRIVATE_KEY_PASSWORD}}
      - name: Unset keys
        if: ${{ always() }}
        run: |
          unset RELEASE_MINISIGN_PRIVATE_KEY
          unset RELEASE_MINISIGN_PRIVATE_KEY_PASSWORD
